# Goal: Try to prevent leakage of credentials and other secrets int ESAPI repo.
#
#
# Execute this workflow every time a new commit is pushed to the ESAPI repo
# or # a PR is submitted to it. Do so regardless of branch.
# on: [push, pull_request]

# If you want to IGNORE secrets in an specifit path(s), then uncomment
# or add something like the following format shown here:
#
# paths-ignore:
#   - "documentation/**
#   - "src/test/**
#
# or just add separate specific files, such as:
#   # Exclude test versions of ESAPI.properties that have Encryptor.MasterKey &
#   # Encryptor.MasterSalt set.
#   - "src/test/resources/esapi/ESAPI.properties"
#   - "src/test/resources/esapi/ESAPI-DualValidatorFileChecker.properties"
#   - "src/test/resources/esapi/ESAPI-QuotedValidatorFileChecker.properties"
#   - "src/test/resources/esapi/ESAPI-SingleValidatorFileChecker.properties"
#   - "src/test/resources/esapi/ESAPI-CommaeValidatorFileChecker.properties"
